"""add duration column

Revision ID: 3e3b53122b4d
Revises: e8f2a1b3c4d5
Create Date: 2026-06-25 11:46:32.005207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3b53122b4d'
down_revision = 'e8f2a1b3c4d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.drop_column('duration_seconds')

    # ### end Alembic commands ###
