"""added tables for user contributed drafts

Revision ID: 593587be480a
Revises: 3e3b53122b4d
Create Date: 2026-07-10 15:06:41.898146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '593587be480a'
down_revision = '3e3b53122b4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concert_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concert_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concert_drafts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_concert_drafts_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_concert_drafts_year'), ['year'], unique=False)

    op.create_table('concert_artist_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concert_draft_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('artist_name', sa.String(length=255), nullable=False),
    sa.Column('instrument', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['concert_draft_id'], ['concert_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concert_artist_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concert_artist_drafts_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concert_artist_drafts_concert_draft_id'), ['concert_draft_id'], unique=False)

    op.create_table('setlist_item_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concert_draft_id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('piece_name', sa.String(length=255), nullable=False),
    sa.Column('raga_name', sa.String(length=255), nullable=True),
    sa.Column('talam_name', sa.String(length=255), nullable=True),
    sa.Column('composer_name', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=True),
    sa.Column('timestamp_seconds', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_draft_id'], ['concert_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concert_draft_id', 'sequence_number', name='unique_concert_draft_sequence')
    )
    with op.batch_alter_table('setlist_item_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setlist_item_drafts_concert_draft_id'), ['concert_draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_setlist_item_drafts_piece_id'), ['piece_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setlist_item_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setlist_item_drafts_piece_id'))
        batch_op.drop_index(batch_op.f('ix_setlist_item_drafts_concert_draft_id'))

    op.drop_table('setlist_item_drafts')
    with op.batch_alter_table('concert_artist_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concert_artist_drafts_concert_draft_id'))
        batch_op.drop_index(batch_op.f('ix_concert_artist_drafts_artist_id'))

    op.drop_table('concert_artist_drafts')
    with op.batch_alter_table('concert_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concert_drafts_year'))
        batch_op.drop_index(batch_op.f('ix_concert_drafts_title'))
        batch_op.drop_index(batch_op.f('ix_concert_drafts_status'))

    op.drop_table('concert_drafts')
    # ### end Alembic commands ###
