"""add ingest_drafts table

Revision ID: 9cfc3496d1a9
Revises: b41d32709cb1
Create Date: 2026-06-11 17:32:47.358208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfc3496d1a9'
down_revision = 'b41d32709cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingest_drafts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.String(length=255), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('timestamp_seconds', sa.Integer(), nullable=True),
    sa.Column('raw_line', sa.Text(), nullable=False),
    sa.Column('parsed_piece', sa.String(length=255), nullable=True),
    sa.Column('parsed_raga', sa.String(length=255), nullable=True),
    sa.Column('parsed_talam', sa.String(length=255), nullable=True),
    sa.Column('parsed_composer', sa.String(length=255), nullable=True),
    sa.Column('parsed_kind', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('resolved_setlist_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_setlist_item_id'], ['setlist_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingest_drafts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingest_drafts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingest_drafts_youtube_id'), ['youtube_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingest_drafts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingest_drafts_youtube_id'))
        batch_op.drop_index(batch_op.f('ix_ingest_drafts_status'))

    op.drop_table('ingest_drafts')
    # ### end Alembic commands ###
