"""initial schema

Revision ID: b41d32709cb1
Revises: 
Create Date: 2026-06-11 16:03:31.541313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b41d32709cb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm')
    op.create_table('artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('composers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('concerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('youtube_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_id')
    )
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concerts_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_concerts_year'), ['year'], unique=False)

    op.create_table('ragas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('talams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('concert_artists',
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=True),
    sa.Column('instrument', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('concert_id'),
    sa.UniqueConstraint('concert_id', 'artist_id', 'instrument', 'role', name='uix_concertartist_artist_instrument_role')
    )
    with op.batch_alter_table('concert_artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concert_artists_artist_id'), ['artist_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_concert_artists_concert_id'), ['concert_id'], unique=False)
        batch_op.create_index('ix_concertartist_artist_role', ['artist_id', 'role'], unique=False)

    op.create_table('pieces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=255), nullable=True),
    sa.Column('raga_id', sa.Integer(), nullable=False),
    sa.Column('composer_id', sa.Integer(), nullable=False),
    sa.Column('talam_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composer_id'], ['composers.id'], ),
    sa.ForeignKeyConstraint(['raga_id'], ['ragas.id'], ),
    sa.ForeignKeyConstraint(['talam_id'], ['talams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name', 'kind', 'raga_id', 'composer_id', 'talam_id', name='uix_piece_name_kind_raga_composer_talam')
    )
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pieces_composer_id'), ['composer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pieces_raga_id'), ['raga_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pieces_talam_id'), ['talam_id'], unique=False)

    op.create_table('piece_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('piece_aliases', schema=None) as batch_op:
        batch_op.create_index('idx_piece_aliases_trgm', ['alias'], unique=False, postgresql_using='gin', postgresql_ops={'alias': 'gin_trgm_ops'})
        batch_op.create_index(batch_op.f('ix_piece_aliases_piece_id'), ['piece_id'], unique=False)

    op.create_table('setlist_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.Column('timestamp_seconds', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['piece_id'], ['pieces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concert_id', 'sequence_number', name='unique_concert_sequence')
    )
    with op.batch_alter_table('setlist_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_setlist_items_concert_id'), ['concert_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_setlist_items_piece_id'), ['piece_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('setlist_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_setlist_items_piece_id'))
        batch_op.drop_index(batch_op.f('ix_setlist_items_concert_id'))

    op.drop_table('setlist_items')
    with op.batch_alter_table('piece_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_piece_aliases_piece_id'))
        batch_op.drop_index('idx_piece_aliases_trgm', postgresql_using='gin', postgresql_ops={'alias': 'gin_trgm_ops'})

    op.drop_table('piece_aliases')
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pieces_talam_id'))
        batch_op.drop_index(batch_op.f('ix_pieces_raga_id'))
        batch_op.drop_index(batch_op.f('ix_pieces_composer_id'))

    op.drop_table('pieces')
    with op.batch_alter_table('concert_artists', schema=None) as batch_op:
        batch_op.drop_index('ix_concertartist_artist_role')
        batch_op.drop_index(batch_op.f('ix_concert_artists_concert_id'))
        batch_op.drop_index(batch_op.f('ix_concert_artists_artist_id'))

    op.drop_table('concert_artists')
    op.drop_table('talams')
    op.drop_table('ragas')
    with op.batch_alter_table('concerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concerts_year'))
        batch_op.drop_index(batch_op.f('ix_concerts_title'))

    op.drop_table('concerts')
    op.drop_table('composers')
    op.drop_table('artists')
    # ### end Alembic commands ###
