"""nullable_piece_fks

Revision ID: d4c3d914c644
Revises: 9cfc3496d1a9
Create Date: 2026-06-11 18:28:41.055725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4c3d914c644'
down_revision = '9cfc3496d1a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.alter_column('raga_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('composer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('talam_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pieces', schema=None) as batch_op:
        batch_op.alter_column('talam_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('composer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('raga_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
